### ISSUE TITLE
Add all currencies

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#10]
create a currency identifiers file and put `currency_identifiers` there. make this into a **dict** instead of list of tuples.

then add all of the ISO 3 letter identifiers from https://en.wikipedia.org/wiki/ISO_4217

remember to include the **Unofficial currency codes**

when searching, instead of checking if to see if each identifier is contained within the currency string, just take lowercase of the first 3 characters (and if fails, then the last 3 characters) and look them up in the dict above.

**Comment by kutakdogan** [comment]
try in this order:
- first 3 characters
- the 3 characters following "iso4217" if found within the ref string
- last 3 characters

**Comment by gpkc** [comment]
https://github.com/gaussian/edgar-data/commit/f061380742b14ccc8302da91c5132fc227a0cabb and https://github.com/gaussian/edgar-data/commit/5df1027bfe95014a7432e787fe342bb5731f2e85
