### ISSUE TITLE
Add supplemental_links

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#15]
Return `list` of tuples: `(link, type, size)`

This should be a part of the `EdgarForm` object

See https://www.sec.gov/Archives/edgar/data/64670/000006467015000005/0000064670-15-000005-index.htm

**Comment by gpkc** [comment]
https://github.com/gaussian/edgar-data/commit/240d0155acc0d49adf99abaf1223e77d28f3f05f

**Comment by kut** [comment]
Thanks - in `_supplemental_links` can you check that the column names are the correct ones when retrieving? To be sure that we are getting the right ones, in the right order. (Name, link and size, correct?)

**Comment by gpkc** [comment]
OK: https://github.com/gaussian/edgar-data/commit/ead1d159d73371daf1aaad01b0713f2a157f9c14
