### ISSUE TITLE
Add ability to choose the XBRL period from XBRL

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#16]
something like
`EdgarForm.xbrl.set_period(this_year=False, this_quarter=False, month=0)`
where only one of those params may be truthy

and if cannot set period, then raise `XbrlPeriodNotFound` exception or something

**Comment by gpkc** [comment]
1st part (QTD): https://github.com/gaussian/edgar-data/commit/196a8dd1d2d2d94ecad203531c881f64a45279e7

**Comment by kut** [comment]
QTD looks good

**Comment by kut** [comment]
seems to be working, but only tested with 1 company so far (pending other fixes like `fiscal_period_focus`)
