### ISSUE TITLE
Did we fix the `Nonetype` bug?

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#18]
In EdgarData.get_form_data for presbia: 'NoneType' object has no attribute 'value'
In EdgarData.get_form_data for Qualstar: 'NoneType' object has no attribute 'value'
In EdgarData.get_form_data for SteadyMed: 'NoneType' object has no attribute 'value'
In EdgarData.get_form_data for eclipse (software): 'NoneType' object has no attribute 'value'

**Comment by kut** [comment]
BTW fix this after the rest of the feature additions

**Comment by gpkc** [comment]
https://github.com/gaussian/edgar-data/commit/c15ebae38bf23e7e4e4dfd1c3f4d3e23063d1194

**Comment by kut** [comment]
Kut to test with live data to make sure problem resolved

**Comment by kut** [comment]
Seems to be resolved
