### ISSUE TITLE
Huge text node

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#19]
In EdgarData.get_form_data for Prologis: xmlSAX2Characters: huge text node, line 102360, column 154 (<string>, line 102360)

In EdgarData.get_form_data for Prologis: xmlSAX2Characters: huge text node, line 101992, column 216 (<string>, line 101992)

**Comment by gpkc** [comment]
Do you know which company caused this?

**Comment by kut** [comment]
Prologis

**Comment by kut** [comment]
fixing this one is lower priority, feel free to get to this last

**Comment by gpkc** [comment]
https://github.com/gaussian/edgar-data/commit/eae9a4fd0300bd04f75953dba26a009df856bfd9

**Comment by kut** [comment]
Kut to test with live data to make sure problem resolved

**Comment by kut** [comment]
Seems to be resolved
