### ISSUE TITLE
Normalize form_type

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#24]
quick update on SEC stuff (real quick)

can you normalize the form type in EdgarForm/EdgarData? so it's always 10K, 8K etc vs 10-K or 10k

`form_type = self.form_type.replace("-", "").replace(" ", "").upper()`

so whenever we pull form type we know it's of that form

**Comment by gpkc** [comment]
Decided to keep them in the form `10-K`, `8-K`, etc

https://github.com/gaussian/edgar-data/commit/179229213e7441c4775c90a21e69c2fe201ea64a
https://github.com/gaussian/edgar-data/commit/ada34e90ff7181b25a12d1ceef510f3c148b6ea1
