### ISSUE TITLE
Retrieve XBRL field values for all available segments for the current period

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#27]
We'll need a new method/property on the `Field` class, in addition to `value()` - called `segment_values()`, which should return a `list` of `(segment_name, segment_value)`

e.g.:
![image](https://user-images.githubusercontent.com/5658236/43022291-bcd0531a-8c34-11e8-90b8-507740ef5e52.png)

**Comment by gpkc** [comment]
https://github.com/gaussian/edgar-data/commit/84c6af130347669a2c4a26ec1b804dec807a3c1a
https://github.com/gaussian/edgar-data/commit/7b1539d033d98f95748c7fc1d1c06ba9438e5fb5
