### ISSUE TITLE
No XBRL found for some forms, can we verify this is true?

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#33]
No XBRL found: org = GasLog Partners, form = 20-F, url = https://www.sec.gov/Archives/edgar/data/1598655/000093041317000414/c87353_20f.htm

No XBRL found: org = PHI Group, form = 10-Q, url = https://www.sec.gov/Archives/edgar/data/704172/000147124214000062/phil10q03312012.htm

No XBRL found: org = Vystar, form = 10-K, url = https://www.sec.gov/Archives/edgar/data/1308027/000114420413035053/v346756_10k.htm

No XBRL found: org = histogenics, form = 10-K, url = https://www.sec.gov/Archives/edgar/data/1372299/000119312515109659/d886285d10k.htm

**Comment by gpkc** [comment]
Looks like none of these have XBRL data indeed:
1: https://www.sec.gov/Archives/edgar/data/1598655/000093041317000414/0000930413-17-000414-index.htm
2: https://www.sec.gov/Archives/edgar/data/704172/000147124214000062/0001471242-14-000062-index.html
3: https://www.sec.gov/Archives/edgar/data/1308027/000114420413035053/0001144204-13-035053-index.html
4: https://www.sec.gov/Archives/edgar/data/1372299/000119312515109659/0001193125-15-109659-index.html

**Comment by kut** [comment]
Got it
