### ISSUE TITLE
Specify which fields to use 

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#49]
Add a param to init of `EdgarData` that is a list that specifies which fields (Revenues, etc) to allow. For performance reasons.

**Comment by kut** [comment]
Should improve performance on #48

**Comment by kut** [comment]
@gpkc I found that when I specify the allowable fields (after the refactoring, #51), suddenly the code fetches no fields at all?

**Comment by gpkc** [comment]
@kut how are you doing that?
Just added a new test, and it's passing:
```
    def test_metric_list(self):
        xbrl = XBRL(XBRL_SIMPLE, metrics_to_load=['Assets', 'GrossProfit'])

        assert 'Assets' in xbrl.fields
        assert 'GrossProfit' in xbrl.fields
        assert 'Revenues' not in xbrl.fields
```

**Comment by kut** [comment]
The following fetches nothing

```
metrics_to_load = ['CostOfRevenue', 'Revenues', 'SalesAndMarketingExpense', 'Assets', 'SellingGeneralAndAdministrativeExpense', 'RentalExpenses', 'RepairsAndMaintenanceExpense', 'GrossProfit', 'ResearchAndDevelopmentExpense', 'NetIncomeAttributableToParent']

self.edgar = EdgarData(metrics_to_load=metrics_to_load
```

**Comment by gpkc** [comment]
@kut I believe the problem was that there were a couple metrics that were missing from the implementation. It should have been raising an error for you.
I have pushed a fix.

**Comment by kut** [comment]
pasting @gpkc comment:

**Comment by kut** [comment]
@gpkc moving back to "in progress" given we need to figure out the metric dependency issue.

please let me know due date too

**Comment by gpkc** [comment]
@kut what is the reason you want to be able to specify which fields to use? Depending on your answer there might be a better solution for what you're looking for.

**Comment by kut** [comment]
Just need to limit the fields to the ones I specified. No real need to be
able to dynamically specify different fields. So I’m ok with hard coding
which fields we can fetch.

**Comment by gpkc** [comment]
@kut so I think that's already in place - check the `metrics_to_facts.py` file under the `XBRL` folder.
The problem with dynamically specifying fields is that I'd need to code some dependency between the fields. It would be useful to obtain some marginal performance if you really need to fetch just a single field or so.

**Comment by kut** [comment]
ok so this is done then
