### ISSUE TITLE
Improve flexibility and output of segment values

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#52]
As we know `segment_values` returns too many values in that `tuple` (and I need to add even more dimensions!). So here’s what we should do:

1) Let’s make the returned list of `tuple` into a list of `dict` (not `namedtuple` - performance is similar from benchmarks plus it allows client to iterate on the keys and saves us from returning a massive sparse array). The key value of the `dict` is determined in (3) below. 

2) If one of the dimensions is `None`, then it shouldn’t have a key in the output dictionary

3) EdgarData should have an internal list of the segment dimensions it can look  it when calculating segment values (eg LegalEntityAxis etc). Whenever we need to add a new dimension, we should be able to just by adding to that list. This list should be a list of `tuple` like this (**the second item in each `tuple` should become the key of the returned `dict` list**):
```
ALLOWED_SEGMENT_DIMENSIONS = [
    (‘ProductOrServiceAxis’, ‘p’),
    (‘ConsolidationItemsAxis’, ‘c’),
    (‘StatementOperatingActivitiesSegmentAxis’, ‘o’),
    (‘StatementGeographicalAxis’, ‘g’),
    (‘LegalEntityAxis’, ‘l’),
    (‘MajorCustomersAxis’, ‘c’),
    (‘StatementBusinessSegmentsAxis’, ‘b’),
    (‘SubsegmentsAxis’, ‘s’),
]
```

4) Here is a key improvement to allow us to accept arbitrary new segment dimensions (e.g. ones that are unique to a company, e.g. `ba:BusinessSegmentsSecondaryAxis` for Boeing):
    **(a)** If we encounter a a duplicate context, we will **not remove** the context from the list (and not add it to `bad_contexts`)
    **(b)** Instead, find all the dimensions in this context that we are not tracking (e.g. `ba:BusinessSegmentsSecondaryAxis`, `lm:BusinessGroupAxis`)
    **(c)** Add each of these dimensions **temporarily** to our list of `ALLOWED_SEGMENT_DIMENSIONS` (or a copy of it). This is a list of `tuple` - both items in the tuple should be the name of the dimension (e.g. `current_allowed_dimensions.append(('lm:BusinessGroupAxis', 'lm:BusinessGroupAxis'))`
    **(d)** Only do this if we do not have too many dimensions (we don't want to hit an infinite loop potentially) - so if `len(current_allowed_dimensions) > 12` then handle the error like we do today (e.g. delete the old duplicate context and add context to `bad_contexts` 
    **(e)** Now that we've expanded the dimensions we're looking for, delete all the contexts that have been found so far, and loop back to the beginning

5) I’ve been seeing some dimensions that look very similar, eg `us-gaap:LegalEntityAxis` and `bsx:LegalEntityAxis`. Or am I crazy? If this isn't already happening, let’s make the segment values code work as you’d expect here - ie we should ignore the part before the colon. Sometimes companies will write their stock ticker (eg bsx) instead of us-gaap

6) Add Boeing and Bank of America to our tests

**Comment by kut** [comment]
@gpkc added some more colour to the above. Does this all make sense?

**Comment by kut** [comment]
@gpkc timing?

**Comment by gpkc** [comment]
@kut Started this today but will have to finish by tomorrow.

**Comment by gpkc** [comment]
@kut so the return value would still be like `[ segment_values, bad_contexts ]`, however the `segment_values` part would now be a list of dictionaries instead of tuples?
Also, where would the segment value itself fit on this? Perhaps a `value` key on the dictionary?
Are the pro forma and nil segment rules still applying (i.e. remove those)?

**Comment by kut** [comment]
Correct - list of dictionaries. 

Yes - let’s have a `_value` key. 

And yes - those same rules still apply.

**Comment by gpkc** [comment]
@kut couldn't work as much as I expected on this today, my bad. It's going well, though. I'll have some time for it tomorrow, and then I believe we'll be ready to ship edgar-data back to production.

**Comment by kut** [comment]
also @gpkc   - there's a bug above - the code for `MajorCustomersAxis` should be `m`

**Comment by kut** [comment]
@gpkc per our Slack convo - let’s not search for context nodes multiple times, and let’s not ever expand the set of context nodes beyond those that contain the baseline contexts we’re interested in (eg ProductOrService)
