### ISSUE TITLE
Could not find valid period for Spire

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#54]
https://visorco.slack.com/archives/C5JCB30LR/p1533967670000055

**Comment by gpkc** [comment]
@kut that's a strange case.
This is the failing document, it's a 10-Q:
https://www.sec.gov/Archives/edgar/data/3146/000112695618000050/lg-20180630.xml
Its period focus is Q2. Therefore its YTD contexts should have approx. 90*2=180 days.
However, most of their contexts have Q3 YTD periods (i.e. 270 days). And by looking at the 10-Q html filename:
https://www.sec.gov/Archives/edgar/data/3146/000112695618000050/spireq3201810-qdoc.htm
It looks like this doc was supposed to be a Q3 doc indeed. Therefore I believe the period focus has a typo.
Not sure how to fix that without being too specific, as this was a human error, apparently.

**Comment by kut** [comment]
Why does the YTD context matter for us? We’re only pulling QTD for
10-Qs...should this be causing a failure for QTD?

**Comment by gpkc** [comment]
@kut
Hmm, currently the default behavior is to pull YTD for all forms, and only pull QTD if `this_quarter` is `True`.
It should work OK for QTD, I ran a simple test here to check that.

**Comment by kut** [comment]
Shouldn’t we make it so it doesn’t pull YTD (or try to) when it doesn’t
need to? Visor makes sure to set the period for all forms before it pulls
XBRL data.

**Comment by kut** [comment]
There are also 3x as many 10Qs as there are 10Ks, so we’re probably being
wasteful if we’re pulling YTD for all forms, no?

**Comment by gpkc** [comment]
@kut How do you set the period before pulling data? The `XBRL` constructor defaults to YTD, and automatically pulls the data.
If you are always doing a `set_period` before accessing field data, I should stop the constructor from pulling YTD automatically. It might improve performance, but you must remember to set the period before accessing the data.

**Comment by gpkc** [comment]
@kut In this case, yes. I simply thought 10-Q YTD data were important too, so left as default similar to how 10-K is handled. It's easy to change that, though.

**Comment by kut** [comment]
Yes let’s do that. I always set the period for every form, either year or
quarter. Probably we can raise an error if the period isn’t set

**Comment by gpkc** [comment]
@kut makes sense. Do you want to open a new Issue for that or should I do that?

**Comment by kut** [comment]
Thanks, you can do that

**Comment by gpkc** [comment]
@kut Didn't open a dedicated issue for that, since I think this one should be enough.
I haven't defined any exceptions for the case when you don't set a period, though, because it's not possible to easily check that when querying the `fields` property. Might leave that for the refactored version.
