### ISSUE TITLE
Return HTML/XBRL as dict

### ISSUE THREAD

**Issue by kutakdogan** [gaussian/edgar-data#6]
Like below:

```
all_filings = {
    'filings': {'K': html_10k, 'Q1': html_q1, etc},
    'xbrls':  {'K': xbrl_10k, 'Q1': xbrl_q1, etc},
    etc...
}
```

**Comment by gpkc** [comment]
Done. Instead of returning dicts I'm returning an object from a class called `Filings`. This class has an `all_filings` method. This method will returns all found filings. To filter out their form types, and get their period end date, do something like that:

```python
docs = sec.get_form_data(...)
for doc in docs.all_filings():
    if doc.form_type == '10-K':
        period = doc.period_end_date
        ticker = doc.fields['TradingSymbol']
        revenue = doc.fields['Revenues']
        # etc...
    elif doc.form_type == '10-Q':
        "do something"
    elif doc.form_type == '8-K':
        "do something"
```

What do you think?

**Comment by kutakdogan** [comment]
Call it FilingsDataset VS Filings so the class is a singular entity VS
plural
