### ISSUE TITLE
How does this perform?

### ISSUE THREAD

**Issue by kut** [gaussian/edgar-data#7]
(1) Let's add the following companies to tests, pulling all their data for years 2015-2018:
- Walmart | United States | Retail | $486 billion
- Sinopec Group | China | Petroleum | $268 billion
- Toyota Motor | Japan | Automobiles | $255 billion
- Volkswagen | Germany | Automobiles | $240 billion
- Royal Dutch Shell | Netherlands (United Kingdom) † | Petroleum | $240 billion
- Berkshire Hathaway | United States | Products | $242 billion
- Apple | United States | Technology | $216 billion
- Exxon Mobil | United States | Petroleum | $205 billion

(2) Test their CIKs are retrieved correctly (the function may struggle because there are many entities with the above names...)

(3) Test that their 2017 revenue matches the above

(4) How long does the above take to run?

**Comment by kutakdogan** [comment]
PS try searching by the company's ticker, more likely for (2) to succeed

**Comment by gpkc** [comment]
I think that Toyota only fills 20-F, as a foreign company:
http://www.toyota-global.com/investors/ir_library/sec/
https://www.sec.gov/cgi-bin/browse-edgar?CIK=TM&owner=exclude&action=getcompany

**Comment by gpkc** [comment]
Could not find XBRL formatted filings on VW:
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001182534&owner=exclude&count=40&hidefilings=0
Ex:
https://www.sec.gov/Archives/edgar/data/1182534/000119312518102939/0001193125-18-102939-index.htm

**Comment by kutakdogan** [comment]
Can you quickly diagnose how much of the 40s is spent on HTTP requests?
That actually sounds quite high, there should only be a small handful of
requests - unless there are dozens of 8-Ks? Can you also check the total
number of 8-Ks returned in the test?

Handling async should be no problem, given that there are many concurrent
worker threads that download simultaneously, but I want to make sure we
don’t have a major optimization we’re missing

**Comment by kutakdogan** [comment]
ok sounds good. let me know how IFRS stuff goes

**Comment by kutakdogan** [comment]
let's add two more companies:
https://finance.yahoo.com/quote/BA/
https://finance.yahoo.com/quote/BSX/

let's also add 3 metrics to the tests:
- net income (already added)
- EBIT (already added)
- gross profit

**Comment by gpkc** [comment]
I guess you can close this as per https://github.com/gaussian/edgar-data/commit/027526cf5d88f0c040f457c476f66df34080b62f
