### ISSUE TITLE
If no calendar_year is provided what to do when retrieving 10k or 20f?

### ISSUE THREAD

**Issue by gpkc** [gaussian/edgar-data#8]
Currently the system only supports retrieving a single 10-K or 20-F form, for a given `calendar_year`. However, if the user provides a date range directly instead, what to do if more than one yearly form is found?

**Comment by kutakdogan** [comment]
hmm it's looking like we need to redo the way we return stuff.

i think we need a class EdgarForm (which has a `type`, `html` and `xbrl` which may be `None`)

**Comment by kutakdogan** [comment]
thus we would return ALL found forms

**Comment by kutakdogan** [comment]
now that we have a class for EdgarForm, i think we should remove FilingsDataset, it no longer has a benefit. we should just return a list of EdgarForm objects.

also, i'd want to consolidate "FilingRetriever" into EdgarData object, there's no semantic difference between them (literally just put code from one into the other)

**Comment by kutakdogan** [comment]
G fixed in c240674c37dc9ffbbc54f552a22b426a8e481d37
